In [1]:
# Python code to illustrate classification using data set 

import pandas as pd 
dataset = pd.read_csv("iris_data.csv", index_col="Unnamed: 0")
data = dataset.iloc[:, :] 

In [2]:
#seperating the predicting column from the whole dataset (taking numpy.ndarray)

X = data.iloc[:, :-1].values        #dependent columns (input_features)  (already in numbers format)
y = dataset.iloc[:, 4].values       #independent column (output_class)   (it is in english text-- need to convert into numbers)

In [3]:
from sklearn.preprocessing import LabelEncoder 

#Encoding the output_class to numbers (total 3 unique class)
labelencoder_y = LabelEncoder() 
encoded_y = labelencoder_y.fit_transform(y) 

In [4]:
from sklearn.model_selection import train_test_split

#Splitting the data into test and train dataset 
X_train, X_test, y_train, y_test = train_test_split(X, encoded_y, test_size = 0.3, random_state = 0) 

#random_state = 0, if we put same number, we will get same split always
#test_size = 0.3, means 30% of all data will be considered as test_data

>> 9 different classification algorithms:
    
    1. RandomForest - Ensemble method
    2. XGBoost
    3. SVM (Support Vector Machine) Classifier
    4. Nearest Neighbors Classifier
    5. Decision tree
    6. SGD (Stochastic Gradient Descent) classifier
    7. Gaussian Naive Bayes
    8. MLP (Multi-layer Perceptron) Neural network
    9. Gaussian Process Classifier

In [5]:
#Using the random forest classifier for the prediction 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

classifier=RandomForestClassifier() #create classifier
classifier=classifier.fit(X_train,y_train) #train our model
predicted=classifier.predict(X_test) #predict our model

#printing the results 
print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
print ('Report : ') 
print (classification_report(y_test, predicted)) 
print ('Predict class for input [5.8, 2.8, 5.1, 2.4] : ',labelencoder_y.inverse_transform(classifier.predict([[5.8, 2.8, 5.1, 2.4]]))[0]) 

Confusion Matrix :
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Accuracy Score : 0.9777777777777777
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

Predict class for input [5.8, 2.8, 5.1, 2.4] :  Iris-virginica


In [6]:
#Using the xgboost classifier for the prediction 
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

classifier = XGBClassifier() #create classifier
classifier=classifier.fit(X_train,y_train) #train our model
predicted=classifier.predict(X_test) #predict our model

#printing the results 
print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
print ('Report : ') 
print (classification_report(y_test, predicted)) 
#print ('Predict class for input [5.8, 2.8, 5.1, 2.4] : ',labelencoder_y.inverse_transform(classifier.predict([[5.8, 2.8, 5.1, 2.4]])))

[20:34:22] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Confusion Matrix :
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Accuracy Score : 0.9777777777777777
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



c:\users\dell pc\appdata\local\programs\python\python38\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


In [7]:
#Using the Support Vector Machine classifier for the prediction 

from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

classifier = SVC() #create classifier
classifier=classifier.fit(X_train,y_train) #train our model
predicted=classifier.predict(X_test) #predict our model

#printing the results 
print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
print ('Report : ') 
print (classification_report(y_test, predicted)) 
print ('Predict class for input [5.8, 2.8, 5.1, 2.4] : ',labelencoder_y.inverse_transform(classifier.predict([[5.8, 2.8, 5.1, 2.4]]))[0]) 

Confusion Matrix :
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Accuracy Score : 0.9777777777777777
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

Predict class for input [5.8, 2.8, 5.1, 2.4] :  Iris-virginica


In [8]:
#Using the Nearest Neighbors classifier for the prediction 

from sklearn import neighbors
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

classifier = neighbors.KNeighborsClassifier() #create classifier
classifier=classifier.fit(X_train,y_train) #train our model
predicted=classifier.predict(X_test) #predict our model

#printing the results 
print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
print ('Report : ') 
print (classification_report(y_test, predicted)) 
print ('Predict class for input [5.8, 2.8, 5.1, 2.4] : ',labelencoder_y.inverse_transform(classifier.predict([[5.8, 2.8, 5.1, 2.4]]))[0]) 

Confusion Matrix :
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Accuracy Score : 0.9777777777777777
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

Predict class for input [5.8, 2.8, 5.1, 2.4] :  Iris-virginica


In [9]:
#Using the Decision Tree for the prediction 

from sklearn import tree
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

classifier = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5) #create classifier
classifier=classifier.fit(X_train,y_train) #train our model
predicted=classifier.predict(X_test) #predict our model

#printing the results 
print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
print ('Report : ') 
print (classification_report(y_test, predicted)) 
print ('Predict class for input [5.8, 2.8, 5.1, 2.4] : ',labelencoder_y.inverse_transform(classifier.predict([[5.8, 2.8, 5.1, 2.4]]))[0]) 

Confusion Matrix :
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Accuracy Score : 0.9777777777777777
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

Predict class for input [5.8, 2.8, 5.1, 2.4] :  Iris-virginica


In [10]:
#Using the SGD Classifier for the prediction 

from sklearn.linear_model import SGDClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

classifier = OneVsRestClassifier(SGDClassifier()) #create classifier
classifier=classifier.fit(X_train,y_train) #train our model
predicted=classifier.predict(X_test) #predict our model

#printing the results 
print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
print ('Report : ') 
print (classification_report(y_test, predicted)) 
print ('Predict class for input [5.8, 2.8, 5.1, 2.4] : ',labelencoder_y.inverse_transform(classifier.predict([[5.8, 2.8, 5.1, 2.4]]))[0]) 

Confusion Matrix :
[[16  0  0]
 [ 0 15  3]
 [ 0  0 11]]
Accuracy Score : 0.9333333333333333
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.83      0.91        18
           2       0.79      1.00      0.88        11

    accuracy                           0.93        45
   macro avg       0.93      0.94      0.93        45
weighted avg       0.95      0.93      0.93        45

Predict class for input [5.8, 2.8, 5.1, 2.4] :  Iris-virginica


In [11]:
#Using the Gaussian Naive Bayes for the prediction 

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

classifier = GaussianNB() #create classifier
classifier=classifier.fit(X_train,y_train) #train our model
predicted=classifier.predict(X_test) #predict our model

#printing the results 
print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
print ('Report : ') 
print (classification_report(y_test, predicted)) 
print ('Predict class for input [5.8, 2.8, 5.1, 2.4] : ',labelencoder_y.inverse_transform(classifier.predict([[5.8, 2.8, 5.1, 2.4]]))[0]) 

Confusion Matrix :
[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
Accuracy Score : 1.0
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Predict class for input [5.8, 2.8, 5.1, 2.4] :  Iris-virginica


In [12]:
#Using the Neural network - Multi-layer Perceptron for the prediction 

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

classifier = MLPClassifier() #create classifier
classifier=classifier.fit(X_train,y_train) #train our model
predicted=classifier.predict(X_test) #predict our model

#printing the results 
print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
print ('Report : ') 
print (classification_report(y_test, predicted)) 
print ('Predict class for input [5.8, 2.8, 5.1, 2.4] : ',labelencoder_y.inverse_transform(classifier.predict([[5.8, 2.8, 5.1, 2.4]]))[0]) 

Confusion Matrix :
[[16  0  0]
 [ 0 16  2]
 [ 0  0 11]]
Accuracy Score : 0.9555555555555556
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.89      0.94        18
           2       0.85      1.00      0.92        11

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45

Predict class for input [5.8, 2.8, 5.1, 2.4] :  Iris-virginica


c:\users\dell pc\appdata\local\programs\python\python38\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [13]:
#Using the Gaussian Process Classifier for the prediction 

from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

classifier = GaussianProcessClassifier() #create classifier
classifier=classifier.fit(X_train,y_train) #train our model
predicted=classifier.predict(X_test) #predict our model

#printing the results 
print ('Confusion Matrix :') 
print(confusion_matrix(y_test, predicted)) 
print ('Accuracy Score :',accuracy_score(y_test, predicted)) 
print ('Report : ') 
print (classification_report(y_test, predicted)) 
print ('Predict class for input [5.8, 2.8, 5.1, 2.4] : ',labelencoder_y.inverse_transform(classifier.predict([[5.8, 2.8, 5.1, 2.4]]))[0]) 

Confusion Matrix :
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
Accuracy Score : 0.9777777777777777
Report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

Predict class for input [5.8, 2.8, 5.1, 2.4] :  Iris-virginica
